Add new fields in User
cosmopolitan-app/cosmopolitan pull request #43
Opened 2019-10-20 22:57 UTC by jairofilho79

fix #37

2019-10-20 23:35 UTC, lubien requested changes

2019-10-21 13:07 UTC, iagocavalcante commented on app/Controllers/Http/UserController.js
> +          'gender',
I think this field is unnecessary

2019-10-22 11:44 UTC, jairofilho79 commented on app/Controllers/Http/UserController.js
> +          'gender',
what field? All four?

2019-10-22 11:54 UTC, iagocavalcante commented on app/Controllers/Http/UserController.js
> +          'gender',
Gender

2019-10-29 13:52 UTC, merged